#Server configuration .....
server:
  port: 9192

#Spring configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abhimicrouser
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  application:
    name: ABHIJEET-USER

#Eureka client configuration .....
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka